runtime: nodejs20

env_variables:
  MONGO_URI: "your_mongodb_connection_string_here"
  JWT_SECRET: "your_super_secret_key_here"
  GEMINI_API_KEY: "AIzaSyBK9NfVqgduUVZuuvhsycxtM4QoodxYhK4"
  # Add any other variables your app needs
